export {default as EditUser} from './Admin/EditUser'
export {default as EditAnnonce} from './Admin/EditAnnonce'
export {default as Content} from '../components/Content'
export {default as AddUser} from './Admin/AddUser'
export {default as Users} from './Admin/Users'
export {default as Annonces} from './Admin/Annonces'
export {default as AddAnnonce} from './Admin/AddAnnonce';
export {default as Inscription} from './Auth/Inscription'
export {default as FormPage} from './Auth/FormPage'
export {default as Annonce} from './Client/Annonce';